url: "https://hp-legume.gbif-staging.org"

# Hi carole - you can comment in below if you want to add google analytics to the staging site with a distinct ID
#siteMeasurements:
  #enable: true # When enabled there will be a popup asking the user for their consent. If they accept then the function "attachMeasurements" will be called. You can overwrite this function by adding a file `/_includes/js/measure.js` and replace the function.
  #GA_ID: "G-39D0RHTSHT" # Your Google analytics ID. Sometimes they start with UA-XXXXX-X other times with G-XXXXXXXX depending on how you set it up
  #termsVersion: "2021-08-09" # A version number for your terms. If you change this, then the users will see the popup again asking them to confirm/reject anew.